services:
  api:
    build:
      context: .
      target: dev
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
  db:
    ports:
      - "5432:5432"
  db_test:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=eventflow_test
    ports:
      - 5433:5432
